// Forge — lets the Voxa voice agent CREATE new connectors at runtime.
//
// Tier-A only (safe): the agent supplies a declarative HTTP *spec* (data, never
// code); forge validates it and writes connectors/<id>/index.mjs from a fixed
// template whose only variable is JSON.stringify(spec). The executable logic
// lives in lib/http-connector.mjs. New tools surface via the existing
// /api/voice/tools merge and reach the orb on its next voice session.
//
// See docs/voxa-connector-forge-plan.md.
import { writeFile, mkdir, rm, appendFile, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { loadConnectors, allConnectors, getConnector, effectiveConfig } from "../../lib/registry.mjs";
import { getState, setState, getAllState } from "../../lib/store.mjs";
import { assertPublicHttps } from "../../lib/http-connector.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONNECTORS_DIR = join(__dirname, "..");
const AUDIT_FILE = join(__dirname, "..", "..", "data", "forge-audit.jsonl");

const RESERVED_IDS = new Set(["forge", "__secrets"]);
const ID_RE = /^[a-z][a-z0-9-]{1,39}$/;
const SECRET_KEY_RE = /^[a-z][a-z0-9_]{1,63}$/;
const ACTION_NAME_RE = /^[a-z][a-z0-9_]{1,63}$/;

function ok(result) { return { result }; }
function err(message) { return { error: message }; }

// Keep only the fields the runtime understands, so junk never lands in the file.
function normalizeSpec(spec) {
  return {
    id: spec.id,
    name: spec.name || spec.id,
    description: spec.description || "",
    icon: spec.icon || "🛠",
    baseUrl: spec.baseUrl,
    secrets: Array.isArray(spec.secrets) ? spec.secrets : [],
    config: Array.isArray(spec.config) ? spec.config : [],
    actions: (spec.actions || []).map((a) => ({
      name: a.name,
      description: a.description || "",
      parameters: a.parameters || { type: "object", properties: {} },
      request: a.request || { method: "GET" },
      ...(a.resultPath ? { resultPath: a.resultPath } : {}),
    })),
  };
}

async function validateSpec(spec) {
  if (!spec || typeof spec !== "object") return "spec object required";
  if (typeof spec.id !== "string" || !ID_RE.test(spec.id))
    return `invalid id "${spec.id}" — use lowercase kebab-case, 2–40 chars`;
  if (RESERVED_IDS.has(spec.id)) return `id "${spec.id}" is reserved`;
  if (typeof spec.baseUrl !== "string") return "baseUrl (https) required";
  try { assertPublicHttps(spec.baseUrl); } catch (e) { return `baseUrl rejected: ${e.message}`; }
  if (!Array.isArray(spec.actions) || spec.actions.length === 0) return "at least one action required";

  // Existing tool names across already-loaded connectors (excluding same id).
  const taken = new Map();
  for (const m of allConnectors()) {
    if (m.id === spec.id) continue;
    for (const a of m.actions) taken.set(a.name, m.id);
  }
  const seen = new Set();
  for (const a of spec.actions) {
    if (typeof a.name !== "string" || !ACTION_NAME_RE.test(a.name))
      return `invalid action name "${a?.name}" — lowercase, [a-z0-9_]`;
    if (!a.name.startsWith(spec.id.replace(/-/g, "_") + "_") && !a.name.startsWith(spec.id + "_"))
      return `action "${a.name}" must be prefixed with the connector id (e.g. ${spec.id.replace(/-/g, "_")}_…)`;
    if (seen.has(a.name)) return `duplicate action "${a.name}" in spec`;
    seen.add(a.name);
    if (taken.has(a.name)) return `action "${a.name}" already owned by connector "${taken.get(a.name)}"`;
    if (a.parameters && (typeof a.parameters !== "object" || (a.parameters.type && a.parameters.type !== "object")))
      return `action "${a.name}".parameters must be an object JSON Schema`;
    if (a.request?.path) {
      try { assertPublicHttps(spec.baseUrl.replace(/\/$/, "") + a.request.path); }
      catch (e) { return `action "${a.name}" path rejected: ${e.message}`; }
    }
  }
  return null;
}

function fileFor(id) { return join(CONNECTORS_DIR, id, "index.mjs"); }

function renderFile(spec) {
  return `// AUTO-GENERATED by the forge connector — do not edit by hand.
// Declarative HTTP connector; logic lives in lib/http-connector.mjs.
// Created ${new Date().toISOString()}.
import { makeHttpConnector } from "../../lib/http-connector.mjs";

export default makeHttpConnector(${JSON.stringify(spec, null, 2)});
`;
}

async function exists(p) { try { await stat(p); return true; } catch { return false; } }

async function audit(entry) {
  try {
    await mkdir(dirname(AUDIT_FILE), { recursive: true });
    await appendFile(AUDIT_FILE, JSON.stringify({ at: new Date().toISOString(), ...entry }) + "\n", "utf8");
  } catch { /* audit is best-effort */ }
}

// Shared create path for every "make a connector" action. Validates, writes the
// file, reloads, enables, and reports — so both the flat forge_rest_get and the
// advanced forge_http_connector funnel through identical, audited logic.
async function createFromSpec(rawSpec, auditAction, overwrite) {
  const problem = await validateSpec(rawSpec);
  if (problem) return err(problem);
  const dir = join(CONNECTORS_DIR, rawSpec.id);
  const file = fileFor(rawSpec.id);
  if (await exists(file)) {
    const existing = getConnector(rawSpec.id);
    if (!overwrite) return err(`connector "${rawSpec.id}" already exists — pass overwrite:true to replace it`);
    if (existing && !existing.forged) return err(`refusing to overwrite non-forged connector "${rawSpec.id}"`);
  }
  const spec = normalizeSpec(rawSpec);
  try {
    await mkdir(dir, { recursive: true });
    await writeFile(file, renderFile(spec), "utf8");
  } catch (e) {
    return err(`failed to write connector file: ${e.message}`);
  }
  await audit({ action: auditAction, id: spec.id, baseUrl: spec.baseUrl, actions: spec.actions.map((a) => a.name) });
  await loadConnectors();
  if (!getConnector(spec.id)) return err(`written but failed to load "${spec.id}" — check the spec; the file was kept for inspection`);
  await setState(spec.id, { enabled: true });
  const secrets = (await getState("__secrets")).config || {};
  const missing = (spec.secrets || []).filter((k) => !secrets[k]);
  return ok(
    [
      `Created connector "${spec.id}" with ${spec.actions.length} action(s): ${spec.actions.map((a) => a.name).join(", ")}.`,
      missing.length ? `Set these secret(s) first with forge_set_secret: ${missing.join(", ")}.` : `All referenced secrets are set.`,
      `Tap the orb to restart the voice session and the new tools will be available.`,
    ].join(" "),
  );
}

// Find {secret:NAME} tokens in a string so the spec can declare its secrets.
function secretsInString(s) {
  const out = [];
  const re = /\{secret:([a-z0-9_]+)\}/gi;
  let m;
  while ((m = re.exec(String(s)))) out.push(m[1]);
  return out;
}

export default {
  id: "forge",
  name: "Forge · Connector builder",
  description:
    "Lets Voxa create new HTTP connectors from a declarative spec at runtime. " +
    "New tools become available on the next voice session.",
  icon: "⚒",
  config: [],

  async test() {
    const forged = allConnectors().filter((m) => m.forged).length;
    return { ok: true, message: `Forge ready. ${forged} forged connector(s) currently loaded.` };
  },

  actions: [
    {
      name: "forge_http_connector",
      description:
        "Create (or overwrite) a connector that calls an HTTPS REST API, described declaratively. " +
        "Reference API keys with {secretRef:'key'} or '{secret:key}' in headers/query and set them via " +
        "forge_set_secret — never put raw keys in the spec. After creating, tell the user to tap the orb " +
        "to restart the voice session so the new tools load.",
      parameters: {
        type: "object",
        properties: {
          id: { type: "string", description: "Unique lowercase kebab-case connector id, e.g. 'openweather'." },
          name: { type: "string", description: "Human-friendly name." },
          description: { type: "string", description: "One-line description." },
          icon: { type: "string", description: "Optional emoji/glyph." },
          baseUrl: { type: "string", description: "HTTPS base URL, e.g. 'https://api.openweathermap.org/data/2.5'." },
          secrets: { type: "array", items: { type: "string" }, description: "Secret keys this connector references." },
          overwrite: { type: "boolean", description: "Replace an existing forged connector with the same id." },
          actions: {
            type: "array",
            description: "The voice tools this connector exposes.",
            items: {
              type: "object",
              properties: {
                name: { type: "string", description: "Globally-unique tool name, prefixed with the connector id (id_…)." },
                description: { type: "string" },
                parameters: { type: "object", description: "JSON Schema (object root) for this action's arguments." },
                request: {
                  type: "object",
                  description: "How to build the HTTP call. Values support {arg} and {secret:key} tokens.",
                  properties: {
                    method: { type: "string", description: "GET|POST|PUT|PATCH|DELETE (default GET)." },
                    path: { type: "string", description: "Appended to baseUrl; supports {arg} templating." },
                    query: { type: "object", description: "Query params; values are templates or {secretRef:'key'}." },
                    headers: { type: "object", description: "Headers; values are templates or {secretRef:'key'}." },
                    body: { type: "object", description: "Request body for non-GET; templated." },
                    bodyType: { type: "string", description: "'json' (default) or 'form'." },
                  },
                },
                resultPath: { type: "string", description: "Dot/index path into the JSON response, e.g. 'weather.0.description'." },
              },
              required: ["name", "description"],
            },
          },
        },
        required: ["id", "name", "baseUrl", "actions"],
      },
      async handler(args) {
        return createFromSpec(args, "forge_http_connector", args.overwrite);
      },
    },

    {
      // Flat, voice-friendly shortcut for the common case: GET a JSON endpoint and
      // return one field. Every parameter is a string or list-of-strings — no
      // nested objects — so the model can fill it reliably from speech and Gemini's
      // function-calling validates it. Covers ~80% of real connectors; reach for
      // forge_http_connector only for POST/bodies/multi-action connectors.
      name: "forge_rest_get",
      description:
        "Create a connector with ONE GET action against an HTTPS JSON API. Use this for simple 'fetch X' " +
        "integrations. For an API key, put '{secret:my_key}' inside a header value (e.g. " +
        "'Authorization: Bearer {secret:my_key}') and set it with forge_set_secret first — never the raw key. " +
        "Only report success if this returns a message starting with 'Created'; otherwise report the error and retry. " +
        "After it succeeds, tell the user to tap the orb to restart the session so the tool loads.",
      parameters: {
        type: "object",
        properties: {
          id: { type: "string", description: "Lowercase kebab-case connector id, e.g. 'advice'." },
          name: { type: "string", description: "Human-friendly name, e.g. 'Advice Slip'." },
          description: { type: "string", description: "One-line description." },
          baseUrl: { type: "string", description: "HTTPS base URL, e.g. 'https://api.adviceslip.com'." },
          path: { type: "string", description: "Path appended to baseUrl, e.g. '/advice'." },
          result_path: { type: "string", description: "Dot/index path to the field to return, e.g. 'slip.advice'. Omit to return the whole JSON." },
          query_keys: { type: "array", items: { type: "string" }, description: "Names of query parameters; each becomes a string argument of the tool (e.g. ['name'] -> ?name=…)." },
          headers: { type: "array", items: { type: "string" }, description: "Fixed headers as 'Name: value' strings, e.g. ['Accept: application/json']. May contain {secret:key}." },
          overwrite: { type: "boolean", description: "Replace an existing forged connector with the same id." },
        },
        required: ["id", "name", "baseUrl", "path"],
      },
      async handler(args) {
        const idSafe = String(args.id || "").replace(/-/g, "_");
        const qkeys = Array.isArray(args.query_keys) ? args.query_keys.filter((k) => typeof k === "string") : [];
        const properties = {};
        const query = {};
        for (const k of qkeys) {
          properties[k] = { type: "string" };
          query[k] = `{${k}}`;
        }
        const headers = {};
        const declaredSecrets = new Set();
        for (const h of Array.isArray(args.headers) ? args.headers : []) {
          const i = String(h).indexOf(":");
          if (i <= 0) continue;
          const key = h.slice(0, i).trim();
          const val = h.slice(i + 1).trim();
          headers[key] = val;
          secretsInString(val).forEach((s) => declaredSecrets.add(s));
        }
        const spec = {
          id: args.id,
          name: args.name || args.id,
          description: args.description || "",
          baseUrl: args.baseUrl,
          secrets: [...declaredSecrets],
          actions: [
            {
              name: `${idSafe}_get`,
              description: args.description || `GET ${args.path}`,
              parameters: { type: "object", properties, ...(qkeys.length ? { required: qkeys } : {}) },
              request: {
                method: "GET",
                path: args.path,
                ...(qkeys.length ? { query } : {}),
                ...(Object.keys(headers).length ? { headers } : {}),
              },
              ...(args.result_path ? { resultPath: args.result_path } : {}),
            },
          ],
        };
        return createFromSpec(spec, "forge_rest_get", args.overwrite);
      },
    },

    {
      name: "forge_list",
      description: "List all loaded connectors, whether each is enabled and forged, and their action names.",
      parameters: { type: "object", properties: {} },
      async handler() {
        const state = await getAllState();
        const list = allConnectors().map((m) => ({
          id: m.id,
          name: m.name,
          enabled: !!state[m.id]?.enabled,
          forged: !!m.forged,
          actions: m.actions.map((a) => a.name),
        }));
        return ok(JSON.stringify(list));
      },
    },

    {
      name: "forge_test",
      description: "Run a connector's connectivity/readiness test by id.",
      parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] },
      async handler({ id }) {
        const m = getConnector(id);
        if (!m) return err(`no connector "${id}"`);
        if (typeof m.test !== "function") return ok(`"${id}" has no test; ${m.actions.length} action(s).`);
        try {
          const r = await m.test(effectiveConfig(m, (await getState(id)).config));
          return ok(`${r?.ok ? "OK" : "NOT READY"} — ${r?.message ?? ""}`);
        } catch (e) {
          return err(`test threw: ${e.message}`);
        }
      },
    },

    {
      name: "forge_enable",
      description: "Enable a connector by id so its tools are exposed.",
      parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] },
      async handler({ id }) {
        if (!getConnector(id)) return err(`no connector "${id}"`);
        await setState(id, { enabled: true });
        return ok(`"${id}" enabled. Restart the voice session to use its tools.`);
      },
    },

    {
      name: "forge_disable",
      description: "Disable a connector by id so its tools are hidden.",
      parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] },
      async handler({ id }) {
        if (!getConnector(id)) return err(`no connector "${id}"`);
        await setState(id, { enabled: false });
        return ok(`"${id}" disabled.`);
      },
    },

    {
      name: "forge_remove",
      description: "Delete a FORGED connector (created by forge) by id, then reload.",
      parameters: { type: "object", properties: { id: { type: "string" } }, required: ["id"] },
      async handler({ id }) {
        const m = getConnector(id);
        if (!m) return err(`no connector "${id}"`);
        if (!m.forged) return err(`"${id}" was not created by forge — refusing to delete it`);
        try {
          await rm(join(CONNECTORS_DIR, id), { recursive: true, force: true });
        } catch (e) {
          return err(`failed to delete: ${e.message}`);
        }
        await audit({ action: "forge_remove", id });
        await loadConnectors();
        return ok(`Removed forged connector "${id}".`);
      },
    },

    {
      name: "forge_reload",
      description: "Re-scan connectors from disk (rarely needed; create/remove already reload).",
      parameters: { type: "object", properties: {} },
      async handler() {
        await loadConnectors();
        return ok(`Reloaded — ${allConnectors().length} connector(s) on disk.`);
      },
    },

    {
      name: "forge_set_secret",
      description:
        "Store an API key/secret by key for connectors to reference. The value is never logged or read back.",
      parameters: {
        type: "object",
        properties: {
          key: { type: "string", description: "Lowercase snake_case key, e.g. 'openweather_key'." },
          value: { type: "string", description: "The secret value." },
        },
        required: ["key", "value"],
      },
      async handler({ key, value }) {
        if (typeof key !== "string" || !SECRET_KEY_RE.test(key)) return err(`invalid key "${key}" — lowercase snake_case`);
        if (typeof value !== "string" || !value) return err("value (non-empty string) required");
        await setState("__secrets", { enabled: true, config: { [key]: value } });
        await audit({ action: "forge_set_secret", key }); // value intentionally omitted
        return ok(`Secret "${key}" stored.`);
      },
    },

    {
      name: "forge_list_secrets",
      description: "List which secret keys are set (values are never returned).",
      parameters: { type: "object", properties: {} },
      async handler() {
        const cfg = (await getState("__secrets")).config || {};
        return ok(JSON.stringify(Object.keys(cfg).map((k) => ({ key: k, set: !!cfg[k] }))));
      },
    },
  ],
};
